// This file is auto-generated by the Vercel build process.
// It injects environment variables into the client-side JavaScript.
// ALWAYS USE PRODUCTION - No sandbox
window.GLOBAL_CASHFREE_ENVIRONMENT = "PRODUCTION";

// Debug information
console.log('Config loaded - Environment:', window.GLOBAL_CASHFREE_ENVIRONMENT);