// This file is auto-generated by the Vercel build process.
// It injects environment variables into the client-side JavaScript.
// TEMPORARY: Set to SANDBOX for debugging the 400 error
window.GLOBAL_CASHFREE_ENVIRONMENT = "SANDBOX";

// Debug information
console.log('Config loaded - Environment:', window.GLOBAL_CASHFREE_ENVIRONMENT);